TARGET = circle celsius2Fahr fahr2Celsius fahr2Celsius2 fahr2Celsius3 limits literal score tirangle

all: ${TARGET} 

circle: $@

celsius2Fahr: $@

fahr2Celsius: $@

fahr2Celsius2: $@

fahr2Celsius3: $@

limits: $@

literal: $@

score:$@

tirangle:$@

clean:
	rm -f ${TARGET}